# vim-paper

# [colors.bright]
# black = "#555555"
# blue = "#1E6FCC"
# cyan = "#158c86"
# green = "#216609"
# magenta = "#5C21A5"
# red = "#CC3E28"
# white = "#AAAAAA"
# yellow = "#B58900"

# [colors.normal]
# black = "#000000"
# blue = "#1E6FCC"
# cyan = "#158c86"
# green = "#216609"
# magenta = "#5C21A5"
# red = "#CC3E28"
# white = "#AAAAAA"
# yellow = "#B58900"

# [colors.primary]
# background = "#F2EEDE"
# foreground = "#000000"

# nvim-grey
[colors.bright]
black = "#000000"
blue = "#1E6FCC"
cyan = "#158c86"
green = "#216609"
magenta = "#5c21a5"
red = "#c4331d"
white = "#ffffff"
yellow = "#b37f02"

[colors.normal]
black = "#000000"
blue = "#1561b8"
cyan = "#007872"
green = "#1C5708"
magenta = "#5C21A5"
red = "#c4331d"
white = "#ffffff"
yellow = "#B58900"

[colors.primary]
background = "#f2f2f2"
foreground = "#000000"

[font]
size = 13.0

[font.normal]
style = "Regular"
# style = "Extended"

family = "iosevka Term"
# family = "Go Mono"
# family = "SF Mono"
# family = "Fira Code"

# disable font smoothing
# defaults -currentHost write -g AppleFontSmoothing -int 0

[[keyboard.bindings]]
chars = "\f"
key = "K"
mode = "~Vi|~Search"
mods = "Command"

[[keyboard.bindings]]
action = "ClearHistory"
key = "K"
mode = "~Vi|~Search"
mods = "Command"

[[keyboard.bindings]]
action = "ResetFontSize"
key = "Key0"
mods = "Command"

[[keyboard.bindings]]
action = "IncreaseFontSize"
key = "Equals"
mods = "Command"

[[keyboard.bindings]]
action = "IncreaseFontSize"
key = "Plus"
mods = "Command"

[[keyboard.bindings]]
action = "IncreaseFontSize"
key = "NumpadAdd"
mods = "Command"

[[keyboard.bindings]]
action = "DecreaseFontSize"
key = "Minus"
mods = "Command"

[[keyboard.bindings]]
action = "DecreaseFontSize"
key = "NumpadSubtract"
mods = "Command"

[[keyboard.bindings]]
action = "Paste"
key = "V"
mods = "Command"

[[keyboard.bindings]]
action = "Copy"
key = "C"
mods = "Command"

[[keyboard.bindings]]
action = "ClearSelection"
key = "C"
mode = "Vi|~Search"
mods = "Command"

[[keyboard.bindings]]
action = "Hide"
key = "W"
mods = "Command"

[[keyboard.bindings]]
action = "HideOtherApplications"
key = "H"
mods = "Command|Alt"

[[keyboard.bindings]]
action = "Minimize"
key = "M"
mods = "Command"

[[keyboard.bindings]]
action = "Quit"
key = "Q"
mods = "Command"

[[keyboard.bindings]]
action = "CreateNewWindow"
key = "N"
mods = "Command"

[[keyboard.bindings]]
action = "ToggleFullscreen"
key = "F"
mods = "Command|Control"

[[keyboard.bindings]]
action = "SearchForward"
key = "F"
mode = "~Search"
mods = "Command"

[[keyboard.bindings]]
action = "SearchBackward"
key = "B"
mode = "~Search"
mods = "Command"

[mouse]
hide_when_typing = true

[terminal.shell]
args = ["-l", "-c", "tmux new -As main"]
program = "/usr/local/bin/zsh"

[window]
dynamic_padding = true
startup_mode = "Fullscreen"

[window.dimensions]
columns = 80
lines = 50

[window.padding]
x = 4
y = 4

[terminal]

[env]
